### ISSUE TITLE
少有用到的css

### ISSUE THREAD

**Issue by taoeer** [taoeer/fe-note#9]
# image-set

让浏览器根据dpr自动选择获取哪种倍率的图片

> [csdn](https://blog.csdn.net/QDY5945/article/details/101538714)
> [mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/image-set())

```css
.img {
    /* 兼容不支持image-set的webview */
    background-image: url('../imgs/@2x/photo@2x.png');
    
    /* 这里可以使用autoprefixer等postcss插件给image-set添加兼容前缀，这里就不加了 */
    background-image: image-set(
        url('./imgs/@2x/photo@2x.png') 2x,
        url('./imgs/@3x/photo@3x.png') 3x
    );
}
```
